title: "Kankakee Community College"
url: https://foundation.kcc.edu
theme: kcc-gem-theme
nav_links:
  - link_text: About
    link_href: 'about'
    button: false
  - link_text: Events
    link_href: 'events'
    button: false
  - link_text: Alumni
    link_href: 'alumni'
    button: false
  - link_text: Scholarships
    link_href: 'scholarships'
    button: false
  - link_text: Contact
    link_href: '#contact'
    button: false
  - link_text: Give
    link_href: 'give'
    button: true
#  - link_text: Example External Link
#    link_href: 'https://example-external-link.com'
#    button: false
#    external: true  <---- #### Add the `external: true` key & value to make an external link ####
#
#### Example sub-nav configuration below #### =============================================================== #
##                                                                                                           ##
##   `link_href:` values must have a single '/' in the link (no '/' in the begining or end of the string)    ##
##                                                                                                           ##
## ========================================================================================================== #
#
#sub-nav_links:
#  - link_text: Sheets
#    link_href: 'reference/gsheets'
#  - link_text: CloudCannon
#    link_href: 'reference/cloudcannon'
#
collections:
  photos:
    output: false
  distinguished_alumnis:
    output: false
  alumnis:
    output: false
  posts:
    output: false
    _hide_content: true
defaults:
- scope:
    path: ''
    type: photos
  values:
    baseurl: ../../
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
- scope:
    path: ''
    type: alumnis
  values:
    baseurl: ../../../
    categories: alumni
- scope:
    path: ''
    type: distinguished_alumnis
  values:
    baseurl: ../../../
    categories: distinguished_alumnis
permalink: pretty
email:
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/assets/adobe/"
  - "gulp-tasks/"
  - "install.sh"
  - "siteicon.png"
  - "ubuntu.18.04.package-lock.json"
  - "webpack.config.js"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  description: "Descriptions are seen by search engines like Google and displayed in search results"


_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
