title: "Kankakee Community College"
url: https://foundation.kcc.edu
public-url: https://foundation.kcc.edu
canonical_baseurl: https://foundation.kcc.edu
site_name: Foundation
theme: kcc-gem-theme-original
port: 3000
timezone: America/Chicago
google-tag_key: GTM-KKZRJB5
nav_links:
  - link_text: About
    link_href: 'about'
    button: false
  - link_text: Events
    link_href: 'events'
    button: false
  - link_text: Alumni
    link_href: 'alumni'
    button: false
  - link_text: Scholarships
    link_href: 'scholarships'
    button: false
  - link_text: Contact
    link_href: '#contact'
    button: false
  - link_text: Give
    link_href: 'give'
    button: true
#  - link_text: Example External Link
#    link_href: 'https://example-external-link.com'
#    button: false
#    external: true  <---- #### Add the `external: true` key & value to make an external link ####
sub-nav_links:
  - link_text: 'Foundation Board'
    link_href: 'about/foundation-board'
  - link_text: Let's Party
    link_href: 'events/fall-fundraiser'
  - link_text: 'Annual Scholarship Event'
    link_href: 'events/annual-scholarship-event'
  - link_text: "President's Circle Dinner"
    link_href: 'events/presidents-circle-dinner'
  - link_text: "Women's Giving Circle"
    link_href: 'events/womens-giving-circle'
  - link_text: 'Distinguished Alumni Award'
    link_href: 'alumni/distinguished-alumni-award'
  - link_text: 'Alumni Stories'
    link_href: 'alumni/alumni-stories'
  - link_text: 'Staff/Retiree Alumni Stories'
    link_href: 'alumni/staff-stories'
  - link_text: 'Century Scholars'
    link_href: 'scholarships/century-scholars'
  - link_text: 'Create a Scholarship'
    link_href: scholarships/create-a-scholarship
  - link_text: "Employee Giving"
    link_href: 'give/employee-giving'
  - link_text: "Planned Giving"
    link_href: 'give/planned-giving'
  - link_text: "President's Circle"
    link_href: 'give/presidents-circle'
  - link_text: "Women's Giving Circle"
    link_href: 'give/womens-giving-circle'

collections:
  photos:
    output: false
  distinguished_alumnis:
    output: false
  alumnis:
    output: false
  accordions:
    output: false
  contacts:
    output: false
defaults:
- scope:
    path: ''
    type: photos
  values:
    baseurl: ../../
- scope:
    path: ''
    type: alumnis
  values:
    baseurl: ../../../
    categories: [alumni]
- scope:
    path: ''
    type: distinguished_alumnis
  values:
    baseurl: ../../../
    categories: [distinguished_alumnis]
permalink: pretty
email:
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

# include:

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "siteicon.png"
  - "webpack.config.js"
  - "/events/annual-fundraiser-gallery.txt"
  - "buildtools/"
  - "postcss.config.js"
  - "look-for-deprecated-bs4-classes.mjs"
  - "look-for-deprecated-bs4-js.mjs"

uploads_dir: "uploads/" # specifies the default uploads directory for CloudCannon

# CloudCannon configurations — (CC config always starts with an underscore "_")
## CloudCannon collections_config: key for configuring all files in a collection
collections_config:
  alumnis:
    _inputs:
      preview_image:
        comment: 'Social media graphic from designers'
      preview_priority:
        type: number
        comment: Priority/order for showing up on the homepage
      sort_name:
        type: text
        comment: Last name then first name (no comma)
## For custom helper comments in CloudCannon — these comments appear next to the front-matter setting they correspond to:
_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  description: "Descriptions are seen by search engines like Google and displayed in search results"
  form_key: Copy and paste the unique string of characters from the BlackBaud embed code and not the full embed code (e.g. 461d247a-4b20-4ef4-8eec-e42b5836cd13)
  form_instructions: (Optional) enter a paragraph of instructions for the form (appears above the form embed) - accepts inline HTML
  form_footer_note: (Optional) enter a paragraph that will appear under the form (e.g. contact info) - accepts inline HTML
  form_custom_wrapper_class: (Optional) enter any classes (separated with spaces) to add to the form's wrapper/parent element
## CloudCannon options for giving users custom styles and editing settings:
_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
  sheet_key:
    hidden: true
  content:
    format: p h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: align-left
    center: center-this-text
    right: align-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
  _block:
    format: p h2 h3 h4 h5 h6 pre address
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: align-left
    center: center-this-text
    right: align-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
  _text:
    bold: true
    italic: true
    removeformat: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
## CloudCannon configuration for custom naming of the parts of the project in the CC GUI:
_explore:
  groups:
    - heading: 'Standalone | Pages'
      collections:
        - pages
    - heading: 'Collections | Data'
## If a collection is omitted from the _explore.collections list it won't show/exist in CloudCannon ##
      collections:
        - accordions
        - alumnis
        - distinguished_alumnis
        - contacts
